import { Product, LeagueInfo } from '@/types'

export const leagues: LeagueInfo[] = [
  {
    id: 'NBA',
    name: 'NBA',
    icon: '🏀',
    color: '#C9082A',
    description: 'Regatas e jerseys dos maiores times',
  },
  {
    id: 'NFL',
    name: 'NFL',
    icon: '🏈',
    color: '#013369',
    description: 'Camisas de futebol americano',
  },
  {
    id: 'MLB',
    name: 'MLB',
    icon: '⚾',
    color: '#002D72',
    description: 'Camisas de baseball',
  },
  {
    id: 'NHL',
    name: 'NHL',
    icon: '🏒',
    color: '#000000',
    description: 'Camisas de hockey no gelo',
  },
  {
    id: 'FUTEBOL',
    name: 'Futebol',
    icon: '⚽',
    color: '#00B894',
    description: 'Clubes e seleções do mundo',
  },
  {
    id: 'RETRO',
    name: 'Retro',
    icon: '🏆',
    color: '#6C5CE7',
    description: 'Clássicas vintage de todas as ligas',
  },
]

export const mockProducts: Product[] = [
  // NBA
  {
    id: '1',
    name: 'Lakers LeBron James #23',
    slug: 'lakers-lebron-james-23',
    description: 'Camisa oficial Los Angeles Lakers - LeBron James #23. Tecnologia Dri-FIT para máximo conforto. Design icônico roxo e dourado.',
    price: 349.90,
    original_price: 449.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA',
    team: 'Los Angeles Lakers',
    player: 'LeBron James',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Roxo', 'Dourado'],
    stock: 50,
    featured: true,
    rating: 4.8,
    review_count: 234,
    video_url: null,
    created_at: '2026-01-15',
  },
  {
    id: '2',
    name: 'Celtics Jayson Tatum #0',
    slug: 'celtics-jayson-tatum-0',
    description: 'Camisa oficial Boston Celtics - Jayson Tatum #0. Verde clássico com detalhes em branco. Tecido premium respirável.',
    price: 329.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA',
    team: 'Boston Celtics',
    player: 'Jayson Tatum',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Verde'],
    stock: 35,
    featured: true,
    rating: 4.7,
    review_count: 189,
    video_url: null,
    created_at: '2026-01-20',
  },
  {
    id: '3',
    name: 'Warriors Stephen Curry #30',
    slug: 'warriors-stephen-curry-30',
    description: 'Camisa oficial Golden State Warriors - Stephen Curry #30. Azul royal com detalhes dourados. O jersey do maior arremessador da história.',
    price: 339.90,
    original_price: 399.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA',
    team: 'Golden State Warriors',
    player: 'Stephen Curry',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Azul', 'Dourado'],
    stock: 40,
    featured: true,
    rating: 4.9,
    review_count: 312,
    video_url: null,
    created_at: '2026-02-01',
  },
  // NFL
  {
    id: '4',
    name: 'Chiefs Patrick Mahomes #15',
    slug: 'chiefs-patrick-mahomes-15',
    description: 'Camisa oficial Kansas City Chiefs - Patrick Mahomes #15. Vermelho vibrante com detalhes em dourado. Tecido resistente para game day.',
    price: 399.90,
    original_price: 499.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL',
    team: 'Kansas City Chiefs',
    player: 'Patrick Mahomes',
    type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Vermelho'],
    stock: 30,
    featured: true,
    rating: 4.9,
    review_count: 267,
    video_url: null,
    created_at: '2026-01-10',
  },
  {
    id: '5',
    name: 'Cowboys Dak Prescott #4',
    slug: 'cowboys-dak-prescott-4',
    description: 'Camisa oficial Dallas Cowboys - Dak Prescott #4. Branca icônica com a estrela azul. America\'s Team.',
    price: 379.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL',
    team: 'Dallas Cowboys',
    player: 'Dak Prescott',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco', 'Azul Marinho'],
    stock: 25,
    featured: false,
    rating: 4.6,
    review_count: 145,
    video_url: null,
    created_at: '2026-01-25',
  },
  {
    id: '6',
    name: '49ers Brock Purdy #13',
    slug: '49ers-brock-purdy-13',
    description: 'Camisa oficial San Francisco 49ers - Brock Purdy #13. Vermelho e dourado clássico da Bay Area.',
    price: 389.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL',
    team: 'San Francisco 49ers',
    player: 'Brock Purdy',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Vermelho'],
    stock: 20,
    featured: true,
    rating: 4.7,
    review_count: 98,
    video_url: null,
    created_at: '2026-02-10',
  },
  // MLB
  {
    id: '7',
    name: 'Yankees Aaron Judge #99',
    slug: 'yankees-aaron-judge-99',
    description: 'Camisa oficial New York Yankees - Aaron Judge #99. Pinstripes icônicos. O clássico do baseball.',
    price: 299.90,
    original_price: 379.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB',
    team: 'New York Yankees',
    player: 'Aaron Judge',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Branco'],
    stock: 45,
    featured: true,
    rating: 4.8,
    review_count: 201,
    video_url: null,
    created_at: '2026-01-05',
  },
  {
    id: '8',
    name: 'Dodgers Shohei Ohtani #17',
    slug: 'dodgers-shohei-ohtani-17',
    description: 'Camisa oficial Los Angeles Dodgers - Shohei Ohtani #17. Azul Dodger Blue. O fenômeno do baseball.',
    price: 319.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB',
    team: 'Los Angeles Dodgers',
    player: 'Shohei Ohtani',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Branco', 'Azul'],
    stock: 55,
    featured: true,
    rating: 4.9,
    review_count: 356,
    video_url: null,
    created_at: '2026-02-15',
  },
  // NHL
  {
    id: '9',
    name: 'Maple Leafs Auston Matthews #34',
    slug: 'maple-leafs-auston-matthews-34',
    description: 'Camisa oficial Toronto Maple Leafs - Auston Matthews #34. Azul royal com o icônico maple leaf.',
    price: 359.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NHL',
    team: 'Toronto Maple Leafs',
    player: 'Auston Matthews',
    type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Azul'],
    stock: 15,
    featured: false,
    rating: 4.6,
    review_count: 87,
    video_url: null,
    created_at: '2026-01-30',
  },
  {
    id: '10',
    name: 'Oilers Connor McDavid #97',
    slug: 'oilers-connor-mcdavid-97',
    description: 'Camisa oficial Edmonton Oilers - Connor McDavid #97. Azul e laranja vibrante do melhor jogador do mundo.',
    price: 369.90,
    original_price: 429.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NHL',
    team: 'Edmonton Oilers',
    player: 'Connor McDavid',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul', 'Laranja'],
    stock: 20,
    featured: true,
    rating: 4.8,
    review_count: 134,
    video_url: null,
    created_at: '2026-02-05',
  },
  // Futebol
  {
    id: '11',
    name: 'Real Madrid Bellingham #5',
    slug: 'real-madrid-bellingham-5',
    description: 'Camisa oficial Real Madrid - Jude Bellingham #5. Branco merengue com detalhes dourados. La Liga.',
    price: 349.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL',
    team: 'Real Madrid',
    player: 'Jude Bellingham',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Branco'],
    stock: 60,
    featured: true,
    rating: 4.9,
    review_count: 445,
    video_url: null,
    created_at: '2026-02-20',
  },
  {
    id: '12',
    name: 'Barcelona Lamine Yamal #19',
    slug: 'barcelona-lamine-yamal-19',
    description: 'Camisa oficial FC Barcelona - Lamine Yamal #19. Blaugrana clássica. O futuro do futebol.',
    price: 339.90,
    original_price: 399.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL',
    team: 'FC Barcelona',
    player: 'Lamine Yamal',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul', 'Grená'],
    stock: 45,
    featured: true,
    rating: 4.8,
    review_count: 378,
    video_url: null,
    created_at: '2026-02-18',
  },
  // Retro
  {
    id: '13',
    name: 'Bulls Michael Jordan #23 Retro',
    slug: 'bulls-michael-jordan-23-retro',
    description: 'Camisa retro Chicago Bulls - Michael Jordan #23. Edição clássica 1996. O GOAT. Peça de colecionador.',
    price: 449.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO',
    team: 'Chicago Bulls',
    player: 'Michael Jordan',
    type: 'retro',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Vermelho', 'Preto'],
    stock: 10,
    featured: true,
    rating: 5.0,
    review_count: 523,
    video_url: null,
    created_at: '2026-01-01',
  },
  {
    id: '14',
    name: 'Brasil Ronaldo #9 Copa 2002',
    slug: 'brasil-ronaldo-9-copa-2002',
    description: 'Camisa retro Seleção Brasileira - Ronaldo #9. Copa do Mundo 2002. O Fenômeno. Penta!',
    price: 399.90,
    original_price: 479.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO',
    team: 'Brasil',
    player: 'Ronaldo',
    type: 'retro',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Amarelo'],
    stock: 15,
    featured: true,
    rating: 4.9,
    review_count: 412,
    video_url: null,
    created_at: '2026-01-08',
  },
  {
    id: '15',
    name: 'Nets Kevin Durant #7',
    slug: 'nets-kevin-durant-7',
    description: 'Camisa Brooklyn Nets - Kevin Durant #7. Design urbano preto e branco. City Edition.',
    price: 319.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA',
    team: 'Brooklyn Nets',
    player: 'Kevin Durant',
    type: 'especial',
    sizes: ['M', 'L', 'XL'],
    colors: ['Preto'],
    stock: 22,
    featured: false,
    rating: 4.5,
    review_count: 76,
    video_url: null,
    created_at: '2026-02-25',
  },
  {
    id: '16',
    name: 'Eagles Jalen Hurts #1',
    slug: 'eagles-jalen-hurts-1',
    description: 'Camisa Philadelphia Eagles - Jalen Hurts #1. Midnight Green. Fly Eagles Fly!',
    price: 389.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL',
    team: 'Philadelphia Eagles',
    player: 'Jalen Hurts',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Verde'],
    stock: 28,
    featured: false,
    rating: 4.7,
    review_count: 132,
    video_url: null,
    created_at: '2026-02-12',
  },
  {
    id: '17',
    name: 'Manchester City Haaland #9',
    slug: 'manchester-city-haaland-9',
    description: 'Camisa Manchester City - Erling Haaland #9. Sky Blue. A máquina de gols da Premier League.',
    price: 359.90,
    original_price: 419.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL',
    team: 'Manchester City',
    player: 'Erling Haaland',
    type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul Claro'],
    stock: 38,
    featured: false,
    rating: 4.8,
    review_count: 256,
    video_url: null,
    created_at: '2026-02-08',
  },
  {
    id: '18',
    name: 'Bucks Giannis #34',
    slug: 'bucks-giannis-34',
    description: 'Camisa Milwaukee Bucks - Giannis Antetokounmpo #34. Verde caçador. The Greek Freak.',
    price: 329.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA',
    team: 'Milwaukee Bucks',
    player: 'Giannis Antetokounmpo',
    type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: ['Verde'],
    stock: 18,
    featured: false,
    rating: 4.6,
    review_count: 98,
    video_url: null,
    created_at: '2026-02-22',
  },
  {
    id: '19',
    name: 'PSG Mbappé #7 Retro',
    slug: 'psg-mbappe-7-retro',
    description: 'Camisa retro PSG - Kylian Mbappé #7. Era dourada de Paris. Azul marinho com detalhes em vermelho.',
    price: 289.90,
    original_price: 349.90,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO',
    team: 'Paris Saint-Germain',
    player: 'Kylian Mbappé',
    type: 'retro',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Azul Marinho'],
    stock: 12,
    featured: false,
    rating: 4.7,
    review_count: 167,
    video_url: null,
    created_at: '2026-01-18',
  },
  {
    id: '20',
    name: 'Packers Jordan Love #10',
    slug: 'packers-jordan-love-10',
    description: 'Camisa Green Bay Packers - Jordan Love #10. Verde e dourado lendário de Green Bay.',
    price: 379.90,
    original_price: null,
    images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL',
    team: 'Green Bay Packers',
    player: 'Jordan Love',
    type: 'titular',
    sizes: ['M', 'L', 'XL'],
    colors: ['Verde', 'Dourado'],
    stock: 22,
    featured: false,
    rating: 4.5,
    review_count: 67,
    video_url: null,
    created_at: '2026-02-28',
  },
  // Additional products
  {
    id: '21', name: 'Suns Kevin Durant #35', slug: 'suns-kevin-durant-35',
    description: 'Camisa Phoenix Suns - Kevin Durant #35. Laranja The Valley edition.',
    price: 349.90, original_price: 419.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA', team: 'Phoenix Suns', player: 'Kevin Durant', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Laranja'], stock: 25, featured: false,
    rating: 4.7, review_count: 143, video_url: null, created_at: '2026-02-15',
  },
  {
    id: '22', name: 'Nuggets Nikola Jokic #15', slug: 'nuggets-nikola-jokic-15',
    description: 'Camisa Denver Nuggets - Nikola Jokic #15. O MVP sérvio.',
    price: 329.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA', team: 'Denver Nuggets', player: 'Nikola Jokic', type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Azul'], stock: 30, featured: false,
    rating: 4.8, review_count: 187, video_url: null, created_at: '2026-01-28',
  },
  {
    id: '23', name: 'Mavericks Luka Doncic #77', slug: 'mavericks-luka-doncic-77',
    description: 'Camisa Dallas Mavericks - Luka Doncic #77. City Edition azul e prata.',
    price: 339.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA', team: 'Dallas Mavericks', player: 'Luka Doncic', type: 'especial',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Azul'], stock: 20, featured: false,
    rating: 4.8, review_count: 201, video_url: null, created_at: '2026-02-03',
  },
  {
    id: '24', name: 'Bills Josh Allen #17', slug: 'bills-josh-allen-17',
    description: 'Camisa Buffalo Bills - Josh Allen #17. Azul royal vibrante.',
    price: 389.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL', team: 'Buffalo Bills', player: 'Josh Allen', type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Azul'], stock: 18, featured: false,
    rating: 4.6, review_count: 89, video_url: null, created_at: '2026-02-14',
  },
  {
    id: '25', name: 'Dolphins Tua Tagovailoa #1', slug: 'dolphins-tua-tagovailoa-1',
    description: 'Camisa Miami Dolphins - Tua Tagovailoa #1. Aqua clássico de Miami.',
    price: 379.90, original_price: 449.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL', team: 'Miami Dolphins', player: 'Tua Tagovailoa', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Aqua'], stock: 22, featured: false,
    rating: 4.5, review_count: 67, video_url: null, created_at: '2026-01-22',
  },
  {
    id: '26', name: 'Ravens Lamar Jackson #8', slug: 'ravens-lamar-jackson-8',
    description: 'Camisa Baltimore Ravens - Lamar Jackson #8. Roxo e preto intimidador.',
    price: 399.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL', team: 'Baltimore Ravens', player: 'Lamar Jackson', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Roxo'], stock: 15, featured: false,
    rating: 4.7, review_count: 112, video_url: null, created_at: '2026-02-19',
  },
  {
    id: '27', name: 'Red Sox Rafael Devers #11', slug: 'red-sox-rafael-devers-11',
    description: 'Camisa Boston Red Sox - Rafael Devers #11. Branca com detalhes vermelhos.',
    price: 289.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB', team: 'Boston Red Sox', player: 'Rafael Devers', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Branco'], stock: 35, featured: false,
    rating: 4.5, review_count: 78, video_url: null, created_at: '2026-01-15',
  },
  {
    id: '28', name: 'Astros Yordan Alvarez #44', slug: 'astros-yordan-alvarez-44',
    description: 'Camisa Houston Astros - Yordan Alvarez #44. Laranja e azul marinho.',
    price: 299.90, original_price: 359.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB', team: 'Houston Astros', player: 'Yordan Alvarez', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Laranja'], stock: 28, featured: false,
    rating: 4.6, review_count: 92, video_url: null, created_at: '2026-02-06',
  },
  {
    id: '29', name: 'Braves Ronald Acuña Jr #13', slug: 'braves-ronald-acuna-jr-13',
    description: 'Camisa Atlanta Braves - Ronald Acuña Jr #13. Navy com detalhes vermelhos.',
    price: 309.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB', team: 'Atlanta Braves', player: 'Ronald Acuña Jr', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Azul Marinho'], stock: 32, featured: false,
    rating: 4.7, review_count: 156, video_url: null, created_at: '2026-01-30',
  },
  {
    id: '30', name: 'Panthers Matthew Tkachuk #19', slug: 'panthers-matthew-tkachuk-19',
    description: 'Camisa Florida Panthers - Matthew Tkachuk #19. Campeões da Stanley Cup.',
    price: 369.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NHL', team: 'Florida Panthers', player: 'Matthew Tkachuk', type: 'titular',
    sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Vermelho'], stock: 12, featured: false,
    rating: 4.8, review_count: 98, video_url: null, created_at: '2026-02-10',
  },
  {
    id: '31', name: 'Bruins David Pastrnak #88', slug: 'bruins-david-pastrnak-88',
    description: 'Camisa Boston Bruins - David Pastrnak #88. Preto e dourado clássico.',
    price: 359.90, original_price: 429.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'NHL', team: 'Boston Bruins', player: 'David Pastrnak', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Preto'], stock: 16, featured: false,
    rating: 4.6, review_count: 73, video_url: null, created_at: '2026-01-25',
  },
  {
    id: '32', name: 'Rangers Artemi Panarin #10', slug: 'rangers-artemi-panarin-10',
    description: 'Camisa New York Rangers - Artemi Panarin #10. Azul clássico de NY.',
    price: 349.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NHL', team: 'New York Rangers', player: 'Artemi Panarin', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Azul'], stock: 14, featured: false,
    rating: 4.5, review_count: 65, video_url: null, created_at: '2026-02-20',
  },
  {
    id: '33', name: 'Liverpool Salah #11', slug: 'liverpool-salah-11',
    description: 'Camisa Liverpool - Mohamed Salah #11. Vermelho icônico de Anfield.',
    price: 349.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL', team: 'Liverpool', player: 'Mohamed Salah', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Vermelho'], stock: 42, featured: false,
    rating: 4.8, review_count: 289, video_url: null, created_at: '2026-02-11',
  },
  {
    id: '34', name: 'Bayern Munich Musiala #42', slug: 'bayern-munich-musiala-42',
    description: 'Camisa Bayern de Munique - Jamal Musiala #42. Vermelho Bavarian.',
    price: 339.90, original_price: 399.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL', team: 'Bayern Munich', player: 'Jamal Musiala', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Vermelho'], stock: 30, featured: false,
    rating: 4.7, review_count: 178, video_url: null, created_at: '2026-01-20',
  },
  {
    id: '35', name: 'Inter de Milão Lautaro #10', slug: 'inter-de-milao-lautaro-10',
    description: 'Camisa Inter de Milão - Lautaro Martínez #10. Nerazzurri listrada.',
    price: 329.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL', team: 'Inter de Milão', player: 'Lautaro Martínez', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Azul', 'Preto'], stock: 25, featured: false,
    rating: 4.6, review_count: 134, video_url: null, created_at: '2026-02-02',
  },
  {
    id: '36', name: 'Argentina Messi #10 Copa 2022', slug: 'argentina-messi-10-copa-2022',
    description: 'Camisa retro Argentina - Lionel Messi #10. Copa do Mundo 2022. Histórica!',
    price: 429.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'Argentina', player: 'Lionel Messi', type: 'retro',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Branco', 'Azul Claro'], stock: 8, featured: false,
    rating: 5.0, review_count: 467, video_url: null, created_at: '2026-01-05',
  },
  {
    id: '37', name: 'Lakers Kobe Bryant #24 Retro', slug: 'lakers-kobe-bryant-24-retro',
    description: 'Camisa retro Lakers - Kobe Bryant #24. Mamba Forever. Edição memorial.',
    price: 479.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'Los Angeles Lakers', player: 'Kobe Bryant', type: 'retro',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Roxo', 'Dourado'], stock: 5, featured: false,
    rating: 5.0, review_count: 389, video_url: null, created_at: '2026-01-12',
  },
  {
    id: '38', name: 'Patriots Tom Brady #12 Retro', slug: 'patriots-tom-brady-12-retro',
    description: 'Camisa retro New England Patriots - Tom Brady #12. A dinastia dos 6 anéis.',
    price: 449.90, original_price: 529.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'New England Patriots', player: 'Tom Brady', type: 'retro',
    sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Azul Marinho'], stock: 10, featured: false,
    rating: 4.9, review_count: 312, video_url: null, created_at: '2026-01-08',
  },
  {
    id: '39', name: 'AC Milan Kaká #22 Retro', slug: 'ac-milan-kaka-22-retro',
    description: 'Camisa retro AC Milan - Kaká #22. Champions League 2007. Rossoneri classic.',
    price: 389.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'AC Milan', player: 'Kaká', type: 'retro',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Vermelho', 'Preto'], stock: 7, featured: false,
    rating: 4.8, review_count: 245, video_url: null, created_at: '2026-01-15',
  },
  {
    id: '40', name: 'Heat Jimmy Butler #22', slug: 'heat-jimmy-butler-22',
    description: 'Camisa Miami Heat - Jimmy Butler #22. Vice City edition rosa e azul.',
    price: 339.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA', team: 'Miami Heat', player: 'Jimmy Butler', type: 'especial',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Rosa', 'Azul'], stock: 19, featured: false,
    rating: 4.7, review_count: 156, video_url: null, created_at: '2026-02-26',
  },
  {
    id: '41', name: 'Knicks Jalen Brunson #11', slug: 'knicks-jalen-brunson-11',
    description: 'Camisa New York Knicks - Jalen Brunson #11. Azul e laranja de NY.',
    price: 329.90, original_price: 379.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'NBA', team: 'New York Knicks', player: 'Jalen Brunson', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Azul', 'Laranja'], stock: 24, featured: false,
    rating: 4.6, review_count: 108, video_url: null, created_at: '2026-02-17',
  },
  {
    id: '42', name: 'Bengals Ja\'Marr Chase #1', slug: 'bengals-jamarr-chase-1',
    description: 'Camisa Cincinnati Bengals - Ja\'Marr Chase #1. Laranja e preto de Cincinnati.',
    price: 389.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL', team: 'Cincinnati Bengals', player: 'Ja\'Marr Chase', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Laranja'], stock: 16, featured: false,
    rating: 4.6, review_count: 87, video_url: null, created_at: '2026-02-09',
  },
  {
    id: '43', name: 'Lions Aidan Hutchinson #97', slug: 'lions-aidan-hutchinson-97',
    description: 'Camisa Detroit Lions - Aidan Hutchinson #97. Honolulu Blue renascido.',
    price: 379.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'NFL', team: 'Detroit Lions', player: 'Aidan Hutchinson', type: 'titular',
    sizes: ['M', 'L', 'XL'], colors: ['Azul'], stock: 20, featured: false,
    rating: 4.5, review_count: 56, video_url: null, created_at: '2026-02-24',
  },
  {
    id: '44', name: 'Phillies Bryce Harper #3', slug: 'phillies-bryce-harper-3',
    description: 'Camisa Philadelphia Phillies - Bryce Harper #3. Vermelho vibrante.',
    price: 299.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB', team: 'Philadelphia Phillies', player: 'Bryce Harper', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Vermelho'], stock: 33, featured: false,
    rating: 4.7, review_count: 145, video_url: null, created_at: '2026-01-28',
  },
  {
    id: '45', name: 'Padres Fernando Tatis Jr #23', slug: 'padres-fernando-tatis-jr-23',
    description: 'Camisa San Diego Padres - Fernando Tatis Jr #23. City Connect marrom e dourado.',
    price: 309.90, original_price: 369.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'MLB', team: 'San Diego Padres', player: 'Fernando Tatis Jr', type: 'especial',
    sizes: ['M', 'L', 'XL'], colors: ['Marrom'], stock: 18, featured: false,
    rating: 4.6, review_count: 98, video_url: null, created_at: '2026-02-13',
  },
  {
    id: '46', name: 'Flamengo Gabigol #9', slug: 'flamengo-gabigol-9',
    description: 'Camisa Flamengo - Gabigol #9. Rubro-negra. A nação rubro-negra.',
    price: 279.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL', team: 'Flamengo', player: 'Gabigol', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Vermelho', 'Preto'], stock: 50, featured: false,
    rating: 4.8, review_count: 345, video_url: null, created_at: '2026-02-01',
  },
  {
    id: '47', name: 'Corinthians Memphis #7', slug: 'corinthians-memphis-7',
    description: 'Camisa Corinthians - Memphis Depay #7. Todo Poderoso Timão.',
    price: 269.90, original_price: 329.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'FUTEBOL', team: 'Corinthians', player: 'Memphis Depay', type: 'titular',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Branco'], stock: 40, featured: false,
    rating: 4.6, review_count: 198, video_url: null, created_at: '2026-01-18',
  },
  {
    id: '48', name: 'Palmeiras Endrick #9 Retro', slug: 'palmeiras-endrick-9-retro',
    description: 'Camisa retro Palmeiras - Endrick #9. Antes de ir para o Real Madrid.',
    price: 299.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'Palmeiras', player: 'Endrick', type: 'retro',
    sizes: ['S', 'M', 'L', 'XL'], colors: ['Verde'], stock: 15, featured: false,
    rating: 4.7, review_count: 167, video_url: null, created_at: '2026-01-22',
  },
  {
    id: '49', name: 'Warriors Klay Thompson #11 Retro', slug: 'warriors-klay-thompson-11-retro',
    description: 'Camisa retro Warriors - Klay Thompson #11. Splash Brothers era.',
    price: 399.90, original_price: 459.90, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'Golden State Warriors', player: 'Klay Thompson', type: 'retro',
    sizes: ['M', 'L', 'XL'], colors: ['Azul'], stock: 8, featured: false,
    rating: 4.8, review_count: 234, video_url: null, created_at: '2026-01-10',
  },
  {
    id: '50', name: 'Spurs Tim Duncan #21 Retro', slug: 'spurs-tim-duncan-21-retro',
    description: 'Camisa retro San Antonio Spurs - Tim Duncan #21. The Big Fundamental.',
    price: 429.90, original_price: null, images: ['/images/placeholder-jersey.jpg'],
    league: 'RETRO', team: 'San Antonio Spurs', player: 'Tim Duncan', type: 'retro',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'], colors: ['Preto'], stock: 6, featured: false,
    rating: 4.9, review_count: 198, video_url: null, created_at: '2026-01-03',
  },
]
