-- =============================================
-- SEED: Times Profissionais por Liga
-- =============================================

-- NBA (30 times)
INSERT INTO teams (name, abbreviation, league, city, primary_color) VALUES
('Atlanta Hawks', 'ATL', 'NBA', 'Atlanta', '#E03A3E'),
('Boston Celtics', 'BOS', 'NBA', 'Boston', '#007A33'),
('Brooklyn Nets', 'BKN', 'NBA', 'Brooklyn', '#000000'),
('Charlotte Hornets', 'CHA', 'NBA', 'Charlotte', '#1D1160'),
('Chicago Bulls', 'CHI', 'NBA', 'Chicago', '#CE1141'),
('Cleveland Cavaliers', 'CLE', 'NBA', 'Cleveland', '#860038'),
('Dallas Mavericks', 'DAL', 'NBA', 'Dallas', '#00538C'),
('Denver Nuggets', 'DEN', 'NBA', 'Denver', '#0E2240'),
('Detroit Pistons', 'DET', 'NBA', 'Detroit', '#C8102E'),
('Golden State Warriors', 'GSW', 'NBA', 'San Francisco', '#1D428A'),
('Houston Rockets', 'HOU', 'NBA', 'Houston', '#CE1141'),
('Indiana Pacers', 'IND', 'NBA', 'Indianapolis', '#002D62'),
('LA Clippers', 'LAC', 'NBA', 'Los Angeles', '#C8102E'),
('Los Angeles Lakers', 'LAL', 'NBA', 'Los Angeles', '#552583'),
('Memphis Grizzlies', 'MEM', 'NBA', 'Memphis', '#5D76A9'),
('Miami Heat', 'MIA', 'NBA', 'Miami', '#98002E'),
('Milwaukee Bucks', 'MIL', 'NBA', 'Milwaukee', '#00471B'),
('Minnesota Timberwolves', 'MIN', 'NBA', 'Minneapolis', '#0C2340'),
('New Orleans Pelicans', 'NOP', 'NBA', 'New Orleans', '#0C2340'),
('New York Knicks', 'NYK', 'NBA', 'New York', '#006BB6'),
('Oklahoma City Thunder', 'OKC', 'NBA', 'Oklahoma City', '#007AC1'),
('Orlando Magic', 'ORL', 'NBA', 'Orlando', '#0077C0'),
('Philadelphia 76ers', 'PHI', 'NBA', 'Philadelphia', '#006BB6'),
('Phoenix Suns', 'PHX', 'NBA', 'Phoenix', '#1D1160'),
('Portland Trail Blazers', 'POR', 'NBA', 'Portland', '#E03A3E'),
('Sacramento Kings', 'SAC', 'NBA', 'Sacramento', '#5A2D81'),
('San Antonio Spurs', 'SAS', 'NBA', 'San Antonio', '#C4CED4'),
('Toronto Raptors', 'TOR', 'NBA', 'Toronto', '#CE1141'),
('Utah Jazz', 'UTA', 'NBA', 'Salt Lake City', '#002B5C'),
('Washington Wizards', 'WAS', 'NBA', 'Washington', '#002B5C')
ON CONFLICT (name, league) DO NOTHING;

-- NFL (32 times)
INSERT INTO teams (name, abbreviation, league, city, primary_color) VALUES
('Arizona Cardinals', 'ARI', 'NFL', 'Glendale', '#97233F'),
('Atlanta Falcons', 'ATL', 'NFL', 'Atlanta', '#A71930'),
('Baltimore Ravens', 'BAL', 'NFL', 'Baltimore', '#241773'),
('Buffalo Bills', 'BUF', 'NFL', 'Buffalo', '#00338D'),
('Carolina Panthers', 'CAR', 'NFL', 'Charlotte', '#0085CA'),
('Chicago Bears', 'CHI', 'NFL', 'Chicago', '#0B162A'),
('Cincinnati Bengals', 'CIN', 'NFL', 'Cincinnati', '#FB4F14'),
('Cleveland Browns', 'CLE', 'NFL', 'Cleveland', '#311D00'),
('Dallas Cowboys', 'DAL', 'NFL', 'Dallas', '#003594'),
('Denver Broncos', 'DEN', 'NFL', 'Denver', '#FB4F14'),
('Detroit Lions', 'DET', 'NFL', 'Detroit', '#0076B6'),
('Green Bay Packers', 'GB', 'NFL', 'Green Bay', '#203731'),
('Houston Texans', 'HOU', 'NFL', 'Houston', '#03202F'),
('Indianapolis Colts', 'IND', 'NFL', 'Indianapolis', '#002C5F'),
('Jacksonville Jaguars', 'JAX', 'NFL', 'Jacksonville', '#006778'),
('Kansas City Chiefs', 'KC', 'NFL', 'Kansas City', '#E31837'),
('Las Vegas Raiders', 'LV', 'NFL', 'Las Vegas', '#000000'),
('Los Angeles Chargers', 'LAC', 'NFL', 'Los Angeles', '#0080C6'),
('Los Angeles Rams', 'LAR', 'NFL', 'Los Angeles', '#003594'),
('Miami Dolphins', 'MIA', 'NFL', 'Miami', '#008E97'),
('Minnesota Vikings', 'MIN', 'NFL', 'Minneapolis', '#4F2683'),
('New England Patriots', 'NE', 'NFL', 'Foxborough', '#002244'),
('New Orleans Saints', 'NO', 'NFL', 'New Orleans', '#D3BC8D'),
('New York Giants', 'NYG', 'NFL', 'East Rutherford', '#0B2265'),
('New York Jets', 'NYJ', 'NFL', 'East Rutherford', '#125740'),
('Philadelphia Eagles', 'PHI', 'NFL', 'Philadelphia', '#004C54'),
('Pittsburgh Steelers', 'PIT', 'NFL', 'Pittsburgh', '#FFB612'),
('San Francisco 49ers', 'SF', 'NFL', 'Santa Clara', '#AA0000'),
('Seattle Seahawks', 'SEA', 'NFL', 'Seattle', '#002244'),
('Tampa Bay Buccaneers', 'TB', 'NFL', 'Tampa', '#D50A0A'),
('Tennessee Titans', 'TEN', 'NFL', 'Nashville', '#0C2340'),
('Washington Commanders', 'WAS', 'NFL', 'Washington', '#5A1414')
ON CONFLICT (name, league) DO NOTHING;

-- MLB (30 times)
INSERT INTO teams (name, abbreviation, league, city, primary_color) VALUES
('Arizona Diamondbacks', 'ARI', 'MLB', 'Phoenix', '#A71930'),
('Atlanta Braves', 'ATL', 'MLB', 'Atlanta', '#CE1141'),
('Baltimore Orioles', 'BAL', 'MLB', 'Baltimore', '#DF4601'),
('Boston Red Sox', 'BOS', 'MLB', 'Boston', '#BD3039'),
('Chicago Cubs', 'CHC', 'MLB', 'Chicago', '#0E3386'),
('Chicago White Sox', 'CWS', 'MLB', 'Chicago', '#27251F'),
('Cincinnati Reds', 'CIN', 'MLB', 'Cincinnati', '#C6011F'),
('Cleveland Guardians', 'CLE', 'MLB', 'Cleveland', '#00385D'),
('Colorado Rockies', 'COL', 'MLB', 'Denver', '#333366'),
('Detroit Tigers', 'DET', 'MLB', 'Detroit', '#0C2340'),
('Houston Astros', 'HOU', 'MLB', 'Houston', '#002D62'),
('Kansas City Royals', 'KC', 'MLB', 'Kansas City', '#004687'),
('Los Angeles Angels', 'LAA', 'MLB', 'Anaheim', '#BA0021'),
('Los Angeles Dodgers', 'LAD', 'MLB', 'Los Angeles', '#005A9C'),
('Miami Marlins', 'MIA', 'MLB', 'Miami', '#00A3E0'),
('Milwaukee Brewers', 'MIL', 'MLB', 'Milwaukee', '#FFC52F'),
('Minnesota Twins', 'MIN', 'MLB', 'Minneapolis', '#002B5C'),
('New York Mets', 'NYM', 'MLB', 'New York', '#002D72'),
('New York Yankees', 'NYY', 'MLB', 'New York', '#003087'),
('Oakland Athletics', 'OAK', 'MLB', 'Oakland', '#003831'),
('Philadelphia Phillies', 'PHI', 'MLB', 'Philadelphia', '#E81828'),
('Pittsburgh Pirates', 'PIT', 'MLB', 'Pittsburgh', '#27251F'),
('San Diego Padres', 'SD', 'MLB', 'San Diego', '#2F241D'),
('San Francisco Giants', 'SF', 'MLB', 'San Francisco', '#FD5A1E'),
('Seattle Mariners', 'SEA', 'MLB', 'Seattle', '#0C2C56'),
('St. Louis Cardinals', 'STL', 'MLB', 'St. Louis', '#C41E3A'),
('Tampa Bay Rays', 'TB', 'MLB', 'St. Petersburg', '#092C5C'),
('Texas Rangers', 'TEX', 'MLB', 'Arlington', '#003278'),
('Toronto Blue Jays', 'TOR', 'MLB', 'Toronto', '#134A8E'),
('Washington Nationals', 'WSH', 'MLB', 'Washington', '#AB0003')
ON CONFLICT (name, league) DO NOTHING;

-- NHL (32 times)
INSERT INTO teams (name, abbreviation, league, city, primary_color) VALUES
('Anaheim Ducks', 'ANA', 'NHL', 'Anaheim', '#F47A38'),
('Arizona Coyotes', 'ARI', 'NHL', 'Tempe', '#8C2633'),
('Boston Bruins', 'BOS', 'NHL', 'Boston', '#FFB81C'),
('Buffalo Sabres', 'BUF', 'NHL', 'Buffalo', '#002654'),
('Calgary Flames', 'CGY', 'NHL', 'Calgary', '#D2001C'),
('Carolina Hurricanes', 'CAR', 'NHL', 'Raleigh', '#CC0000'),
('Chicago Blackhawks', 'CHI', 'NHL', 'Chicago', '#CF0A2C'),
('Colorado Avalanche', 'COL', 'NHL', 'Denver', '#6F263D'),
('Columbus Blue Jackets', 'CBJ', 'NHL', 'Columbus', '#002654'),
('Dallas Stars', 'DAL', 'NHL', 'Dallas', '#006847'),
('Detroit Red Wings', 'DET', 'NHL', 'Detroit', '#CE1126'),
('Edmonton Oilers', 'EDM', 'NHL', 'Edmonton', '#041E42'),
('Florida Panthers', 'FLA', 'NHL', 'Sunrise', '#041E42'),
('Los Angeles Kings', 'LAK', 'NHL', 'Los Angeles', '#111111'),
('Minnesota Wild', 'MIN', 'NHL', 'Saint Paul', '#154734'),
('Montreal Canadiens', 'MTL', 'NHL', 'Montreal', '#AF1E2D'),
('Nashville Predators', 'NSH', 'NHL', 'Nashville', '#FFB81C'),
('New Jersey Devils', 'NJD', 'NHL', 'Newark', '#CE1126'),
('New York Islanders', 'NYI', 'NHL', 'Elmont', '#00539B'),
('New York Rangers', 'NYR', 'NHL', 'New York', '#0038A8'),
('Ottawa Senators', 'OTT', 'NHL', 'Ottawa', '#C52032'),
('Philadelphia Flyers', 'PHI', 'NHL', 'Philadelphia', '#F74902'),
('Pittsburgh Penguins', 'PIT', 'NHL', 'Pittsburgh', '#FCB514'),
('San Jose Sharks', 'SJS', 'NHL', 'San Jose', '#006D75'),
('Seattle Kraken', 'SEA', 'NHL', 'Seattle', '#001628'),
('St. Louis Blues', 'STL', 'NHL', 'St. Louis', '#002F87'),
('Tampa Bay Lightning', 'TBL', 'NHL', 'Tampa', '#002868'),
('Toronto Maple Leafs', 'TOR', 'NHL', 'Toronto', '#003E7E'),
('Vancouver Canucks', 'VAN', 'NHL', 'Vancouver', '#00205B'),
('Vegas Golden Knights', 'VGK', 'NHL', 'Las Vegas', '#B4975A'),
('Washington Capitals', 'WSH', 'NHL', 'Washington', '#041E42'),
('Winnipeg Jets', 'WPG', 'NHL', 'Winnipeg', '#041E42')
ON CONFLICT (name, league) DO NOTHING;

-- FUTEBOL (~30 clubes principais - Europa + Brasil)
INSERT INTO teams (name, abbreviation, league, city, primary_color) VALUES
-- Brasil
('Flamengo', 'FLA', 'FUTEBOL', 'Rio de Janeiro', '#E40613'),
('Corinthians', 'COR', 'FUTEBOL', 'Sao Paulo', '#000000'),
('Palmeiras', 'PAL', 'FUTEBOL', 'Sao Paulo', '#006437'),
('Sao Paulo FC', 'SPF', 'FUTEBOL', 'Sao Paulo', '#FF0000'),
('Santos', 'SAN', 'FUTEBOL', 'Santos', '#000000'),
('Fluminense', 'FLU', 'FUTEBOL', 'Rio de Janeiro', '#880E35'),
('Vasco da Gama', 'VAS', 'FUTEBOL', 'Rio de Janeiro', '#000000'),
('Botafogo', 'BOT', 'FUTEBOL', 'Rio de Janeiro', '#000000'),
('Gremio', 'GRE', 'FUTEBOL', 'Porto Alegre', '#0091D0'),
('Internacional', 'INT', 'FUTEBOL', 'Porto Alegre', '#E30613'),
('Atletico Mineiro', 'CAM', 'FUTEBOL', 'Belo Horizonte', '#000000'),
('Cruzeiro', 'CRU', 'FUTEBOL', 'Belo Horizonte', '#003DA5'),
-- Europa
('Real Madrid', 'RMA', 'FUTEBOL', 'Madrid', '#FEBE10'),
('Barcelona', 'BAR', 'FUTEBOL', 'Barcelona', '#A50044'),
('Manchester United', 'MUN', 'FUTEBOL', 'Manchester', '#DA291C'),
('Manchester City', 'MCI', 'FUTEBOL', 'Manchester', '#6CABDD'),
('Liverpool', 'LIV', 'FUTEBOL', 'Liverpool', '#C8102E'),
('Chelsea', 'CHE', 'FUTEBOL', 'London', '#034694'),
('Arsenal', 'ARS', 'FUTEBOL', 'London', '#EF0107'),
('Tottenham', 'TOT', 'FUTEBOL', 'London', '#132257'),
('Juventus', 'JUV', 'FUTEBOL', 'Turin', '#000000'),
('AC Milan', 'ACM', 'FUTEBOL', 'Milan', '#FB090B'),
('Inter Milan', 'INT', 'FUTEBOL', 'Milan', '#010E80'),
('PSG', 'PSG', 'FUTEBOL', 'Paris', '#004170'),
('Bayern Munich', 'BAY', 'FUTEBOL', 'Munich', '#DC052D'),
('Borussia Dortmund', 'BVB', 'FUTEBOL', 'Dortmund', '#FDE100'),
('Ajax', 'AJX', 'FUTEBOL', 'Amsterdam', '#D2122E'),
('Benfica', 'BEN', 'FUTEBOL', 'Lisbon', '#FF0000'),
('Porto', 'POR', 'FUTEBOL', 'Porto', '#003F8A'),
('Napoli', 'NAP', 'FUTEBOL', 'Naples', '#009FE3')
ON CONFLICT (name, league) DO NOTHING;
